firebase/php-jwt

Authentication/JWT.php
README.md
tests/JWTTest.php

In addition to allowing users to lock their JWT class into supporting exactly one specific method at runtime (i.e. when their configuration is loaded) with a sane default, I also locked things down a little bit.
First, http://php.net/manual/en/mbstring.overload.php `mbstring.func_overload` can lead to incorrect results from `strlen()` treating string as UTF-8 instead of binary, which can reduce the cost of brute force for an invalid authentication signature.
Second, if `hash_equals()` exists, use that instead of a PHP-land implementation.

Allow users to lock their app into an algorithm.

---

composer.json

target-dir was meant to allow using the root of the package as a PSR-4 root and make composer prepend the target dir when installing to make it compatible with PSR-0, before PSR-4 was a reality.
This setting is deprecated in Composer in favor of using PSR-4, and it is not needed anyway when using the classmap autoloading.

Remove the useless target-dir setting from the composer config

---

Authentication/JWT.php
README.md
tests/JWTTest.php

I noticed there was a minor difference on the server generationg the JWT and the server decoding it (on an openid connect project) and althoug the difference is within millisecs, very often the iat verification failed so I had to read up at the documentation and verify there is some recomendation at least for the exp and the nbf. so I've considered adding a leeway time to all time verifications.
Sources: 
http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#nbfDef
http://openid.net/specs/openid-connect-core-1_0.html#IDToken

Provide a leeway in verification of times to account for clock skew

---

Authentication/JWT.php
tests/JWTTest.php

When using the library with a large number of keys (ie. user specific keys), having to load all available keys is not efficient. 
This change allows to pass an ArrayAccess instance to perform dynamic lookups of the requested key without having to load all available keys.
Let me know if I should amend anything.

Allow using \ArrayAccess as $key in \JWT::decode

---

Authentication/JWT.php
tests/JWTTest.php

Some services require additional info to be sent in the JOSE header, adding the option for encoding.

Adding optional headers to send in JWT

---

Exceptions/BeforeValidException.php
Exceptions/ExpiredException.php
Exceptions/SignatureInvalidException.php
README.md
composer.json
src/BeforeValidException.php
src/ExpiredException.php
src/JWT.php
src/SignatureInvalidException.php
tests/JWTTest.php

Puts the jwt class under the `\Firebase\JWT` namespace.
There is more discussion here: https://github.com/firebase/php-jwt/issues/52
I chose this namespace scheme to match another firebase php library: https://github.com/firebase/firebase-token-generator-php/tree/master/src

Add firebase\jwt namespace

---

src/JWT.php

When i was trying out this library i came across some inconsistencies in the code documentation. I took the liberty to clarify and correct some of the code docs where needed.
Feel free to close if deemed unnecessary.

Aligned the DocBlocks

---

Authentication/JWT.php
src/JWT.php
tests/JWTTest.php

In testing this library for use on a project, I was surprised when JWT::decode returned a successfully decoded payload even when an empty key was supplied.  I mistakenly supplied an empty key b/c I accidentally referred to it in a config file by the wrong name.
I would think that an empty key should be an error.  Otherwise, it would be possible to deploy an application using this library and have all tokens be successfully decoded, regardless of what key was used to encode them.  As mentioned above, this could happen through accidental mishandling of configuration files.
I could be wrong about this and an empty key might be possible by design.  If so, nevermind, and I'll just be more careful. ;-)
I've made the code changes to JWT::decode and added 2 new tests to verify that empty keys …

require a non-empty key to decode a JWT

---

src/JWT.php

The docblock states that null is a possible value for $key, however, it clearly results in an exception.

Remove null as possible key value in docblock

---

run-tests.sh

The extra newline trips a warning in lintian when packaging for Debian,
so just remove it.

Remove newline at beginning of run-tests.sh

---

src/JWT.php

I am unit testing an application where I want to assert that certain JWT values will in fact be marked as 'expired' or 'not ready' but it is proving difficult due to the dynamic values within JWT::decode() method generated by time().
This PR allows a static property to be specified, fixing the value of 'current time' for the test suite.

Use static $timestamp instead of time()

---

src/JWT.php
tests/JWTTest.php

**Use InvalidArgumentException when $allowed_algs is not array**
> Exception thrown if an argument is not of the expected type.
http://php.net/manual/en/class.invalidargumentexception.php
**Use RuntimeExceptions for exceptions related with unencoded data.**
RuntimeExceptions is the correct exception error source is the decoded data.
Note LogicExceptions as defined in PHP documentation implies a modification in the code by the developer.
> Exception that represents error in the program logic. This kind of exception should lead directly to a fix in your code.
http://php.net/manual/en/class.logicexception.php
But the token is a data provided by an external source which is out side of the control of the developer so there is no way of prevent malformed tokens.
```
try {} catch (\Exception) {} …
```

Fix exceptions classes

---

src/JWT.php

Enables developers to extend the class and override variables / methods if they so require.

Add in support for late static binding

---

src/JWT.php

No backward compatibility breaks, just add support for RS384 and RS512 algorithms.
This should help tick more boxes on jwt.io
I've just signed the CLA

Support RS384 and RS512

---

README.md

An example with RS256 with encode and decode.
Keys are created by openssl and inline to make the example complete as single file.
```shell
openssl genrsa -out private.key 1024
openssl rsa -in private.key -pubout > pubkey.key
```

example for RS256 openssl

---

src/JWT.php

if 'kid' value is not found in the given key map, should throw an exception.
Instead, it was outputting a php warning for using an undefined index, resulting in a null key.

bugfix: 'kid' not in given key list

---

src/JWT.php

Related to issue #99 Unknown JSON error
[`json_last_error_msg()`](http://php.net/manual/en/function.json-last-error-msg.php) is not used because it would break compatibility with PHP < 5.5. 
This solution supports all error types until 5.5, keeping compatibility with previous versions.

Add the proper Exception message for all JSON error types by PHP

---

src/JWT.php
tests/JWTTest.php

Detect invalid Base64 encoding in signature

---

README.md

Quickly addresses #109, but a better solution would be to warn the user if they're using `RSA` and we don't see any new lines in their private key.

Add new line warning to README

---

src/JWT.php

Apple Push Notifications require the JWT algorithm be ES256. It still uses OpenSSL and SHA256 just like RS256, but the algorithm name in the headers must be "ES256" or else the token is rejected as invalid. This simple change adds support for ES256 and improves documentation regarding supported algorithms, which should close #183. I tested this locally, and this change alone allowed me to sent APNs, while I could not without this change.

Implement #183: Add ES256 support for Apple Push Notifications

---

src/JWT.php

None of the other if-statements have this extra whitespace. Is this used to signal something, or is this simply a style discrepancy?

Remove extra whitespace in if

---

README.md

Changed $token to $payload, at first sight it is not clearly why "$token" is names as $token since this "$token" represents the payload of the JWT.

Changed $token to $payload

---

src/JWT.php

`json_last_error()` was introduced in PHP 5.3.0, which is a requirement for this package. Hence, the existence check is no longer needed.

Use json_last_error without unnecessary existence check

---

src/JWT.php

It's a minor clarification of input parameters in `JWT::decode` method. 
Second parameter (key) accepts arrays, strings and resources, but in PHPDoc resource type is not listed.
Let's take a look at an example:
```php
<?php
$pubkey =<<<PUBKEY
-----BEGIN PUBLIC KEY-----
[...]
-----END PUBLIC KEY-----
PUBKEY;
$publicKey = openssl_pkey_get_public(pubkey); // $publicKey is a resource
$decodedToken = JWT::decode($token, $publicKey, ['RS256']);
```
If I run static analysis with PHPStan, I will get the following error:
```
Parameter #2 $key of static method Firebase\JWT\JWT::decode() expects array|string, resource given.
```

Add resource type as 2nd param in decode method

---

composer.json
tests/JWTTest.php

It is possible to run with the latest `phpunit` that goes with each version of PHP.
To keep supporting the very old versions of PHP and `phpunit` I  had to add some version checks in the unit tests to choose whether to use `setExpectedException` or `expectException`. That could also probably be done with `method_exists`
What do you think about this approach, using modern versions of `phpunit` where we can?

Allow composer to choose the latest phpunit major version matching each PHP version

---

src/JWK.php
tests/JWKTest.php

This PR introduces changes made in the fork https://github.com/fproject/php-jwt to add support for JWKs, so that a fork is no longer needed. I didn't change the code from that repo apart from updating the docblock at the top of the JWK class, and breaking out the JWK tests into a new file JWKTest.php. Some spacing was also added to those tests to make the arrange/act/assert pattern clear.
I haven't done a ton of manual testing on this, but I assume since the fproject fork has been used, this is a working implementation (and the unit tests pass of course).
Fixes #70.
I know it's a bit weird to make a PR for someone else's code, but since there didn't seem to be any movement on #70 for making one I figured I'd start one so there can be a discussion about what further changes need to be made …

Adding JWK support

---

src/JWT.php
tests/JWTTest.php

1) remove unused variables from unit test code (those tests expect an exception, there is no need to assign the result to a variable)
2) fix a typo in PHP doc

Cleanup code

---

.gitattributes

Currently `firebase/php-jwt/.github/actions/entrypoint.sh` is also loaded via composer install.
This change removes it again.

Add `/.github export-ignore` to .gitattributes

---

src/JWT.php
tests/JWTTest.php

See https://github.com/firebase/php-jwt/issues/369

fix: phpdoc and exception

---

src/JWT.php

Adds previously undocumented `DomainException` to the throws list in the doc-comment of the `JWT::decode` method.
This hotfixes the issue mentioned in #312 and #378.
See #312 for detailed info.

JWT::decode: doc-comment for DomainException added

---

README.md
src/JWK.php
src/JWT.php
tests/JWKTest.php

`parseKey` should return a `Key` object instead of `array|resource`
This PR also updates a lot of return types that were incorrect in `phpdoc`

feat!: update return type for JWK methods

---

src/JWT.php

fix: correct order for hash_equals

---

src/JWT.php

The param $alg is missing on the php doc block for method encode() in class JWT (It ain't much but it's honest work)

Add missing doc block for $alg in JWT::encode()

---

src/JWT.php
tests/JWTTest.php

fix: add flag to force object

---

src/JWT.php
tests/JWTTest.php

Reverts firebase/php-jwt#416
The change broke existing code that wasn't expecting the payload to be converted to object form... final JWT payload should be able to contain arrays

Revert "fix: add flag to force object"

---

README.md
src/JWT.php
tests/JWKTest.php
tests/JWTTest.php

This PR fixes two minor style inconsistencies:
1. Short array syntax is used in the README (used in all code since https://github.com/firebase/php-jwt/pull/385)
2. Single quotes are used for strings where possible (that seems to been the project standard)
Style aspects like this should preferably be enforced by code analysis tools (like `php-cs-fixer`).

Fix style for consistency

---

src/CachedKeySet.php
src/JWK.php
tests/CachedKeySetTest.php
tests/JWKTest.php

Add parameter to `JWK::parseKeySet` and `JWK::parseKey` to prevent "missing alg" error.
```php
$defaultAlg = 'RS256'; // default algorithm used when "alg" isn't set
$jwks = JWK::parseKeySet($jwks, $defaultAlg);
```
See https://github.com/firebase/php-jwt/pull/376/files#r861654996

feat: add defaultAlg param

---

README.md
src/JWT.php

It's almost five years later, but better late than never!
Fixes #188

chore(docs): add examples for exception handling

---

src/JWT.php

This PHP doc sentence is misleading in regards to the actual PHPdoc and typehint.

chore(docs): encode does not accept objects

---

composer.json

- Before `PHP 7.2` version is released, the `sodium` extension is not included in the core PHP extension, it can also add the `ext-sodium` extension in the suggest block to remind developers when using the `PHP 7.0` and `PHP 7.1` versions.

Add ext-sodium to improve suggest block

---

tests/CachedKeySetTest.php
tests/JWKTest.php
tests/JWTTest.php

- Using the `assertSame` to make assert equals strict.

Using the assertSame to make assert equals strict

---

src/CachedKeySet.php
tests/CachedKeySetTest.php

addresses #481 
Calls `JWK::parseKey` on the matching key instead of calling `JWK::parseKeySet` on the whole response

feat: improve caching by only decoding jwks when necessary

---

src/JWT.php

Skip null checks when input is never null

---

README.md

Is it worth making sure we return the headers from `decodeHeaders` as an array?
Headers often have dashed key names and in order to access them currently, the user will have to do: `$cls->{'x-header-key'}`.
In order to make sure we return array, I think it's best to add a default argument to `JWT::jsonDecode` which forwards the second param to `\json_decode()`.

chore(docs): example of unsafe header decode in README

---

src/JWT.php
tests/JWTTest.php

Fixes https://github.com/firebase/php-jwt/issues/504

fix: Allow KID index '0'

---

README.md

Under the section: https://github.com/firebase/php-jwt#exception-handling
```php
try {
$decoded = JWT::decode($payload, $keys);
} catch (LogicException $e) {
// errors having to do with environmental setup or malformed JWT Keys
} catch (UnexpectedValueException $e) {
// errors having to do with JWT signature and claims
}
```
Added imports to this section.

Added fix for the import docs

---

src/JWT.php

See #475 
> and haven't correctly used the nbf claim
I interpret it as having no nbf claim set. So it was always intended as a fallback.

fix: only check iat if nbf is not used

---

src/CachedKeySet.php
tests/CachedKeySetTest.php

fixes https://github.com/firebase/php-jwt/issues/499

fix: handle invalid http responses

---

src/JWK.php
tests/JWKTest.php
tests/data/ec-jwkset.json

Add support for P-384 curve

---

src/JWT.php

This makes #488 work without having to set leeway.

accept float claims but round down to ignore them

---

tests/JWTTest.php

Adds tests for https://github.com/firebase/php-jwt/pull/492 and https://github.com/firebase/php-jwt/pull/493

chore: add tests for latest fixes

---

src/JWT.php
tests/JWTTest.php

Addresses https://github.com/firebase/php-jwt/issues/514

chore: BeforeValidException message for decode

---

src/JWT.php
tests/JWTTest.php

Addresses https://github.com/firebase/php-jwt/issues/530
Allows the `typ` header to be customized via the `$head` parameter in `JWT::encode`.
The usecase here is that some specs require a different required value for the `typ` header. These use cases include CPoP.

feat: allow typ override header

---

.github/workflows/tests.yml

For the moment blocked by https://github.com/phpspec/prophecy/pull/608
We can add `--ignore-platform-reqs` to get around this, but for now we can wait for `phpspec/prophecy`.

chore(ci): add php 8.3

---

src/JWT.php
tests/JWTTest.php

fixes https://github.com/firebase/php-jwt/issues/559

chore: remove jwt incorrect key warning

---

.github/workflows/tests.yml
README.md
composer.json
tests/CachedKeySetTest.php

Additionally:
- drop support for `guzzlehttp/guzzle:v6`
- drop support for `psr/cache:v1` and add support for `psr/cache:v3` (dev only)

chore: drop support for PHP 7.4

---

src/CachedKeySet.php
tests/CachedKeySetTest.php

fixes https://github.com/firebase/php-jwt/issues/543
Without setting the cached item expiry every time, the expiry is not persisted. In order to address this, we cache an array instead of an integer for the rate limit in the `CachedKeySet` class.

fix: ensure ratelimit expiry is set every time

---

.php-cs-fixer.dist.php
src/CachedKeySet.php
src/JWK.php
src/JWT.php

This pull-request contains three commits:
**[chore: fix latest php-cs-fixer findings](https://github.com/firebase/php-jwt/commit/8b0a51bf13ca77a131e8124aab9632a9f40b8734)**
This ensures clean cgl state using the current php-cs-fixer version and ruleset.
**[chore: Mitigate PHP8.4 deprecation warnings (#570)](https://github.com/firebase/php-jwt/commit/7c7f4bce5570f9f7f18906ce0082deb4b64f68ee)**
This change replaces implicitly nullable method arguments by making them explicitly nullable to mitigate PHP8.4 deprecation warnings.
**[chore: Enable php-cs-fixer rules to avoid implicitly nullable method arguments](https://github.com/firebase/php-jwt/commit/0df848cdcd548021309c541dbb370dae6763fbe1)**
This change enables two rules in the php-cs-fixer ruleset to guard against future implicitly method …

chore: Prepare towards PHP8.4 compatibility

---

.github/workflows/tests.yml

Adds PHP 8.4 to the CI matrix.
See #572 and #578
This is marked as `deps` so that release-please picks it up.
The previously added support for PHP 8.4 was done as `chore` and therefore not released.

fix: support php 8.4

---

.github/workflows/tests.yml
src/JWT.php

Fixes failing phpstan errors in #583

chore: fix phpstan

---

README.md

With PHP 8.x, the first example b0rks:
```
PHP Fatal error:  Uncaught Error: Firebase\JWT\JWT::decode(): Argument #3 ($headers) could not be passed by reference in REDACTED.php:26
Stack trace:
#0 {main}
thrown in REDACTED/test.php on line 26
```

Fix example to avoid fatal error

---

src/JWK.php
tests/JWKTest.php
tests/data/octet-jwkset.json

Resolves https://github.com/firebase/php-jwt/issues/555

Parse octet typed JWK

---

README.md

fixing typo on Readme about JWT Decode parameter from `$payload` to `$jwt`.
before fixed: 
```php
JWT::decode($payload, $key);
```
after fixed: 
```php
JWT::decode($jwt, $key);
```

fix: readme or documentation about decoding jwt

---

src/JWT.php

This is a follow-up to https://github.com/firebase/php-jwt/pull/492 where an inconsistency was introduced. When triggering these error messages, if the value should be rounded up, then the value in the error message won't match the value being checked. Given we're talking about fractions of a second, this shouldn't cause any real-world impact. This inconsistency may make debugging edge cases difficult, leading to confusion. This confusion may lead do setting too much leeway in timing settings.

fix: update error text for consistency

---

src/JWT.php

DateTime::ISO8601 has been deprecated since PHP 7.2

fix: use ATOM instead of ISO8601 in exception message
